model_list:
  - model_name: ollama-llama2
    litellm_params:
      model: ollama/llama2
      api_base: http://ai-ollama:11434

  - model_name: ollama-mistral
    litellm_params:
      model: ollama/mistral
      api_base: http://ai-ollama:11434

  - model_name: ollama-codellama
    litellm_params:
      model: ollama/codellama
      api_base: http://ai-ollama:11434

litellm_settings:
  drop_params: true
  set_verbose: true
  success_callback: ["langfuse"]
  
general_settings:
  master_key: ${LITELLM_MASTER_KEY}
  database_url: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
