model_list:
  - model_name: llama3.2
    litellm_params:
      model: ollama/llama3.2:3b
      api_base: http://ollama:11434
      stream: true
      
  - model_name: nomic-embed
    litellm_params:
      model: ollama/nomic-embed-text
      api_base: http://ollama:11434

litellm_settings:
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]
  cache: true
  cache_params:
    type: "redis"
    host: "dify-redis"
    port: 6379
    password: "b26c1bf75738445dea13de6bd33e05cc"

general_settings:
  master_key: sk-13d48a8dc30e6e92c0c2ffa7302481c885d0d412abfb22b46c757589ce4c111c
  database_url: "sqlite:////app/data/litellm.db"
  store_model_in_db: true
